/vol0004/ra000012/data/wahib/gnn/pytorch/scripts/fujitsu/fccbuild/lib/python3.9/site-packages/numpy-1.22.4+3.gcd007c4-py3.9-linux-aarch64.egg/numpy/core/getlimits.py:499: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/vol0004/ra000012/data/wahib/gnn/pytorch/scripts/fujitsu/fccbuild/lib/python3.9/site-packages/numpy-1.22.4+3.gcd007c4-py3.9-linux-aarch64.egg/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/vol0004/ra000012/data/wahib/gnn/pytorch/scripts/fujitsu/fccbuild/lib/python3.9/site-packages/numpy-1.22.4+3.gcd007c4-py3.9-linux-aarch64.egg/numpy/core/getlimits.py:499: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/vol0004/ra000012/data/wahib/gnn/pytorch/scripts/fujitsu/fccbuild/lib/python3.9/site-packages/numpy-1.22.4+3.gcd007c4-py3.9-linux-aarch64.egg/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
Traceback (most recent call last):
  File "/vol0004/ra000012/data/wahib/gnn/super_gnn/submit_scripts_at_fugaku/ogbn-arixv/submit_scripts/../../../examples/graphsage/train.py", line 101, in <module>
    data = load_data(config)
  File "/vol0004/ra000012/data/wahib/gnn/pytorch/scripts/fujitsu/fccbuild/lib/python3.9/site-packages/super_gnn-0.1-py3.9.egg/super_gnn/data_manager/DataLoader.py", line 234, in load_data
  File "/vol0004/ra000012/data/wahib/gnn/pytorch/scripts/fujitsu/fccbuild/lib/python3.9/site-packages/super_gnn-0.1-py3.9.egg/super_gnn/data_manager/DataLoader.py", line 20, in load_graph_structures
  File "/vol0004/ra000012/data/wahib/gnn/pytorch/scripts/fujitsu/fccbuild/lib/python3.9/site-packages/numpy-1.22.4+3.gcd007c4-py3.9-linux-aarch64.egg/numpy/lib/npyio.py", line 407, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'home/ra000012/a04083/gnn/gnn/GNN_benchmark/self_benchmark/a64fx/dataset/ogbn_arxiv_undirected/ogbn_arxiv_2_part/p001-arxiv_nodes.npy'
